-- AlterTable
ALTER TABLE `diary` MODIFY `date` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `emotion` MODIFY `date` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `user_challenge` MODIFY `start_date` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
